local SurvivalConfig = {}

SurvivalConfig.World = {
	Seed = 9173,
	SpawnAreaHalfSize = 640,
	SpawnPoint = Vector3.new(0, 0, 24),
	RespawnHeight = 1.35,
	Performance = {
		ResourceSpawnMultiplier = 0.65,
		StarterSupplyMultiplier = 0.7,
		LandmarkDetailMultiplier = 0.72,
		MaxLandmarkPointLights = 20,
		EnableWorldPostEffects = false,
		UseFutureLighting = false,
		ToneDownSmoothSurfaces = true,
	},
	Terrain = {
		Enabled = true,
		TileSize = 40,
		SmoothResolution = 4,
		MeshExtentScale = 1.18,
		PrimaryNoiseScale = 152,
		SecondaryNoiseScale = 54,
		PrimaryAmplitude = 20,
		SecondaryAmplitude = 9,
		EdgeFalloff = 18,
		HeightClampMin = -10,
		HeightClampMax = 38,
		SpawnFlattenRadius = 170,
		RegionFlattenRadius = 180,
	},
	DayLengthSeconds = 480,
	NightStart = 18.5,
	NightEnd = 6,
	WeatherIntervalSeconds = 80,
	RegionDiscoveryRadius = 118,
	StarterSupplyRadius = 54,
}

SurvivalConfig.Regions = {
	{
		Id = "CinderHarbour",
		DisplayName = "Cinder Harbour",
		Center = Vector3.new(0, 0, 16),
		Radius = 128,
		Description = "A burnt-out survivor landing site on the volcanic coast.",
		Danger = 1,
	},
	{
		Id = "AshwoodHollow",
		DisplayName = "Ashwood Hollow",
		Center = Vector3.new(-315, 0, -315),
		Radius = 118,
		Description = "A dead ash forest thick with ember spores and dark shrines.",
		Danger = 2,
	},
	{
		Id = "SaltcragShores",
		DisplayName = "Saltcrag Shores",
		Center = Vector3.new(330, 0, -300),
		Radius = 118,
		Description = "Jagged sea cliffs studded with salt crystal formations.",
		Danger = 2,
	},
	{
		Id = "ScorchPitQuarry",
		DisplayName = "Scorch Pit Quarry",
		Center = Vector3.new(-360, 0, 305),
		Radius = 114,
		Description = "An abandoned mine with lava fissures and burnt scaffolding.",
		Danger = 3,
	},
	{
		Id = "BrimstoneMarsh",
		DisplayName = "Brimstone Marsh",
		Center = Vector3.new(360, 0, 325),
		Radius = 114,
		Description = "A toxic sulfur swamp with glowing yellow pools.",
		Danger = 3,
	},
	{
		Id = "GlacierScar",
		DisplayName = "Glacier Scar",
		Center = Vector3.new(-585, 0, -35),
		Radius = 108,
		Description = "A frozen anomaly in the volcanic island, ancient relics locked in ice.",
		Danger = 4,
	},
	{
		Id = "DeadMansCaldera",
		DisplayName = "Dead Man's Caldera",
		Center = Vector3.new(585, 0, 35),
		Radius = 108,
		Description = "The open maw of the island's main volcano. Most dangerous place.",
		Danger = 5,
	},
	{
		Id = "MoltenSpireHold",
		DisplayName = "Molten Spire Hold",
		Center = Vector3.new(10, 0, -565),
		Radius = 112,
		Description = "A fortress built on volcanic rock by survivors who came before.",
		Danger = 4,
	},
}

SurvivalConfig.Vitals = {
	Max = 100,
	TickSeconds = 2,
	HungerLoss = 0.55,
	ThirstLoss = 0.8,
	TemperatureDrift = 0.12,
	StarvingDamage = 3,
	DehydratedDamage = 5,
	ColdDamage = 4,
	HeatDamage = 3,
	ColdThreshold = 35,
	HotThreshold = 95,
	ComfortLow = 58,
	ComfortHigh = 82,
}

SurvivalConfig.Items = {
	Wood = { DisplayName = "Wood", Category = "Resource" },
	Leaves = { DisplayName = "Leaves", Category = "Resource" },
	Stone = { DisplayName = "Stone", Category = "Resource" },
	Fiber = { DisplayName = "Fiber", Category = "Resource" },
	Hide = { DisplayName = "Hide", Category = "Resource" },
	IronOre = { DisplayName = "Iron Ore", Category = "Resource" },
	IronIngot = { DisplayName = "Iron Ingot", Category = "Resource" },
	AncientScrap = { DisplayName = "Ancient Scrap", Category = "Resource" },
	MedicinalHerb = { DisplayName = "Medicinal Herb", Category = "Resource" },
	RawMeat = { DisplayName = "Raw Meat", Category = "Food" },
	Berries = { DisplayName = "Berries", Category = "Food" },
	Mushrooms = { DisplayName = "Mushrooms", Category = "Food" },
	CookedBerries = { DisplayName = "Cooked Berries", Category = "Food" },
	CookedMeat = { DisplayName = "Cooked Meat", Category = "Food" },
	MushroomStew = { DisplayName = "Mushroom Stew", Category = "Food" },
	Bandage = { DisplayName = "Bandage", Category = "Medical" },
	Antidote = { DisplayName = "Antidote", Category = "Medical" },
	SurvivalTonic = { DisplayName = "Survival Tonic", Category = "Medical" },
	StoneAxe = { DisplayName = "Stone Axe", Category = "Tool" },
	Pickaxe = { DisplayName = "Pickaxe", Category = "Tool" },
	Spear = { DisplayName = "Spear", Category = "Weapon" },
	IronSpear = { DisplayName = "Iron Spear", Category = "Weapon" },
	HideArmor = { DisplayName = "Hide Armor", Category = "Armor" },
	IronArmor = { DisplayName = "Iron Armor", Category = "Armor" },
	FurVest = { DisplayName = "Fur Vest", Category = "Armor", Description = "A warm vest sewn from animal fur. Helps resist cold." },
	CampfireKit = { DisplayName = "Campfire Kit", Category = "Buildable" },
	TorchStandKit = { DisplayName = "Torch Stand Kit", Category = "Buildable" },
	ShelterKit = { DisplayName = "Shelter Kit", Category = "Buildable" },
	WoodenWallKit = { DisplayName = "Wooden Wall Kit", Category = "Buildable" },
	WoodenDoorKit = { DisplayName = "Wooden Door Kit", Category = "Buildable" },
	WoodenStairsKit = { DisplayName = "Wooden Stairs Kit", Category = "Buildable" },
	StorageChestKit = { DisplayName = "Storage Chest Kit", Category = "Buildable" },
	WatchtowerKit = { DisplayName = "Watchtower Kit", Category = "Buildable" },
	RainCollectorKit = { DisplayName = "Rain Collector Kit", Category = "Buildable" },
	WorkbenchKit = { DisplayName = "Workbench Kit", Category = "Buildable" },
	ForgeKit = { DisplayName = "Forge Kit", Category = "Buildable" },
	SpikeTrapKit = { DisplayName = "Spike Trap Kit", Category = "Buildable" },
	SignalBeaconKit = { DisplayName = "Signal Beacon Kit", Category = "Buildable" },
}

SurvivalConfig.Resources = {
	Tree = {
		DisplayName = "Tree",
		Reward = "Wood",
		MinAmount = 2,
		MaxAmount = 5,
		RequiredTool = "StoneAxe",
		HarvestHits = 4,
		SecondaryRewards = {
			{ Item = "Leaves", Min = 1, Max = 3 },
		},
		SpawnCount = 58,
		RespawnSeconds = 55,
		HarvestText = "Chop",
	},
	Rock = {
		DisplayName = "Rock",
		Reward = "Stone",
		MinAmount = 1,
		MaxAmount = 4,
		RequiredTool = "Pickaxe",
		HarvestHits = 4,
		SpawnCount = 52,
		RespawnSeconds = 65,
		HarvestText = "Mine",
	},
	FiberPlant = {
		DisplayName = "Fiber Plant",
		Reward = "Fiber",
		MinAmount = 2,
		MaxAmount = 4,
		SpawnCount = 46,
		RespawnSeconds = 45,
		HarvestText = "Gather",
	},
	BerryBush = {
		DisplayName = "Berry Bush",
		Reward = "Berries",
		MinAmount = 2,
		MaxAmount = 5,
		SpawnCount = 42,
		RespawnSeconds = 50,
		HarvestText = "Pick",
	},
	WaterSpring = {
		DisplayName = "Water Spring",
		Thirst = 38,
		MinAmount = 1,
		MaxAmount = 1,
		SpawnCount = 14,
		RespawnSeconds = 14,
		HarvestText = "Drink",
	},
	IronDeposit = {
		DisplayName = "Iron Deposit",
		Reward = "IronOre",
		MinAmount = 1,
		MaxAmount = 3,
		SpawnCount = 26,
		RespawnSeconds = 95,
		HarvestText = "Mine",
		RequiredTool = "Pickaxe",
		HarvestHits = 5,
	},
	HerbPatch = {
		DisplayName = "Medicinal Herb",
		Reward = "MedicinalHerb",
		MinAmount = 1,
		MaxAmount = 2,
		SpawnCount = 30,
		RespawnSeconds = 60,
		HarvestText = "Gather",
	},
	MushroomCluster = {
		DisplayName = "Mushroom Cluster",
		Reward = "Mushrooms",
		MinAmount = 1,
		MaxAmount = 3,
		SpawnCount = 26,
		RespawnSeconds = 70,
		HarvestText = "Pick",
	},
	LootCache = {
		DisplayName = "Abandoned Cache",
		SpawnCount = 18,
		RespawnSeconds = 120,
		HarvestText = "Search",
		Loot = {
			{ Item = "AncientScrap", Min = 1, Max = 2, Weight = 36 },
			{ Item = "IronOre", Min = 1, Max = 2, Weight = 24 },
			{ Item = "Bandage", Min = 1, Max = 1, Weight = 18 },
			{ Item = "CookedBerries", Min = 1, Max = 2, Weight = 12 },
			{ Item = "SurvivalTonic", Min = 1, Max = 1, Weight = 10 },
		},
	},
	HouseLoot = {
		DisplayName = "Ruined House Stash",
		SpawnCount = 12,
		RespawnSeconds = 155,
		HarvestText = "Loot",
		Loot = {
			{ Item = "Wood", Min = 3, Max = 6, Weight = 20 },
			{ Item = "Fiber", Min = 2, Max = 4, Weight = 16 },
			{ Item = "Stone", Min = 2, Max = 4, Weight = 12 },
			{ Item = "Bandage", Min = 1, Max = 2, Weight = 14 },
			{ Item = "CookedMeat", Min = 1, Max = 2, Weight = 10 },
			{ Item = "AncientScrap", Min = 1, Max = 3, Weight = 16 },
			{ Item = "IronOre", Min = 1, Max = 2, Weight = 12 },
		},
	},
}

SurvivalConfig.Crafting = {
	StoneAxe = {
		DisplayName = "Stone Axe",
		Cost = { Wood = 2, Stone = 3, Fiber = 1 },
		Result = "StoneAxe",
		Amount = 1,
		Description = "Improves wood and fiber harvesting.",
	},
	Pickaxe = {
		DisplayName = "Pickaxe",
		Cost = { Wood = 3, Stone = 4, Fiber = 1 },
		Result = "Pickaxe",
		Amount = 1,
		Description = "Required for mining rocks and iron deposits.",
	},
	Spear = {
		DisplayName = "Spear",
		Cost = { Wood = 3, Stone = 2, Fiber = 2 },
		Result = "Spear",
		Amount = 1,
		Description = "A longer reach weapon for night stalkers.",
	},
	WorkbenchKit = {
		DisplayName = "Workbench Kit",
		Cost = { Wood = 8, Stone = 4, Fiber = 3 },
		Result = "WorkbenchKit",
		Amount = 1,
		Description = "Unlocks advanced weapons, armor, and crafting stations.",
	},
	WoodenWallKit = {
		DisplayName = "Wooden Wall Kit",
		Cost = { Wood = 8, Leaves = 2, Fiber = 2 },
		Result = "WoodenWallKit",
		Amount = 1,
		Description = "Places a sturdy wall segment for a starter base.",
	},
	WoodenDoorKit = {
		DisplayName = "Wooden Door Kit",
		Cost = { Wood = 7, Fiber = 1 },
		Result = "WoodenDoorKit",
		Amount = 1,
		Description = "Places an openable door frame for your shelter.",
	},
	WoodenStairsKit = {
		DisplayName = "Wooden Stairs Kit",
		Cost = { Wood = 7 },
		Result = "WoodenStairsKit",
		Amount = 1,
		Description = "Places stairs for raised floors and watch posts.",
	},
	StorageChestKit = {
		DisplayName = "Storage Chest Kit",
		Cost = { Wood = 8, Fiber = 2 },
		Result = "StorageChestKit",
		Amount = 1,
		Description = "Stores and withdraws resource stacks at camp.",
	},
	WatchtowerKit = {
		DisplayName = "Watchtower Kit",
		Cost = { Wood = 18, Stone = 4, Fiber = 6 },
		Result = "WatchtowerKit",
		Amount = 1,
		RequiresNearby = "Workbench",
		RequiredLevel = 2,
		Description = "Places a raised lookout tower for team camps.",
	},
	ForgeKit = {
		DisplayName = "Forge Kit",
		Cost = { Stone = 12, Wood = 5 },
		Result = "ForgeKit",
		Amount = 1,
		RequiresNearby = "Workbench",
		RequiredLevel = 2,
		Description = "Smelts ore into ingots.",
	},
	SpikeTrapKit = {
		DisplayName = "Spike Trap Kit",
		Cost = { Wood = 5, Stone = 4, Fiber = 2 },
		Result = "SpikeTrapKit",
		Amount = 1,
		RequiresNearby = "Workbench",
		RequiredLevel = 2,
		Description = "Place to damage night stalkers that cross it.",
	},
	SignalBeaconKit = {
		DisplayName = "Signal Beacon Kit",
		Cost = { IronIngot = 4, AncientScrap = 3, Fiber = 4 },
		Result = "SignalBeaconKit",
		Amount = 1,
		RequiresNearby = "Workbench",
		RequiredLevel = 4,
		Description = "Place and upgrade to survive the final raid.",
	},
	IronIngot = {
		DisplayName = "Iron Ingot",
		Cost = { IronOre = 3, Wood = 1 },
		Result = "IronIngot",
		Amount = 1,
		RequiresNearby = "Forge",
		RequiredLevel = 2,
		Description = "Refined metal for stronger gear.",
	},
	IronSpear = {
		DisplayName = "Iron Spear",
		Cost = { IronIngot = 3, Wood = 2, Fiber = 2 },
		Result = "IronSpear",
		Amount = 1,
		RequiresNearby = "Workbench",
		RequiredLevel = 3,
		Description = "A durable weapon for longer nights.",
	},
	HideArmor = {
		DisplayName = "Hide Armor",
		Cost = { Hide = 4, Fiber = 4 },
		Result = "HideArmor",
		Amount = 1,
		Description = "Reduces damage from enemies.",
	},
	FurVest = {
		DisplayName = "Fur Vest",
		Cost = { Fur = 6, Fiber = 3 },
		Result = "FurVest",
		Amount = 1,
		RequiredLevel = 2,
		Description = "Sewn from rabbit fur. Provides warmth and light protection.",
	},
	IronArmor = {
		DisplayName = "Iron Armor",
		Cost = { IronIngot = 5, Hide = 2, Fiber = 3 },
		Result = "IronArmor",
		Amount = 1,
		RequiresNearby = "Workbench",
		RequiredLevel = 4,
		Description = "Heavy armor with strong protection and durability.",
	},
	CampfireKit = {
		DisplayName = "Campfire Kit",
		Cost = { Wood = 4, Stone = 2 },
		Result = "CampfireKit",
		Amount = 1,
		Description = "Place to warm nearby players at night.",
	},
	TorchStandKit = {
		DisplayName = "Torch Stand Kit",
		Cost = { Wood = 2, Stone = 1, Fiber = 1 },
		Result = "TorchStandKit",
		Amount = 1,
		Description = "A permanent light marker for roads, camps, and gates.",
	},
	ShelterKit = {
		DisplayName = "Shelter Kit",
		Cost = { Wood = 10, Leaves = 4, Fiber = 6 },
		Result = "ShelterKit",
		Amount = 1,
		Description = "Place to reduce cold exposure nearby.",
	},
	RainCollectorKit = {
		DisplayName = "Rain Collector Kit",
		Cost = { Wood = 5, Fiber = 4, Stone = 1 },
		Result = "RainCollectorKit",
		Amount = 1,
		Description = "Place to collect emergency drinking water.",
	},
	CookedBerries = {
		DisplayName = "Cooked Berries",
		Cost = { Berries = 3 },
		Result = "CookedBerries",
		Amount = 1,
		RequiresNearby = "Campfire",
		Description = "Restores more hunger and thirst than raw berries.",
	},
	CookedMeat = {
		DisplayName = "Cooked Meat",
		Cost = { RawMeat = 2 },
		Result = "CookedMeat",
		Amount = 1,
		RequiresNearby = "Campfire",
		Description = "A strong meal from defeated night stalkers.",
	},
	MushroomStew = {
		DisplayName = "Mushroom Stew",
		Cost = { Mushrooms = 3, Berries = 1 },
		Result = "MushroomStew",
		Amount = 1,
		RequiresNearby = "Campfire",
		Description = "Warm food that restores hunger, thirst, and a little health.",
	},
	Bandage = {
		DisplayName = "Bandage",
		Cost = { Fiber = 4, Berries = 1 },
		Result = "Bandage",
		Amount = 1,
		Description = "Restores health over time.",
	},
	Antidote = {
		DisplayName = "Antidote",
		Cost = { MedicinalHerb = 2, Berries = 2 },
		Result = "Antidote",
		Amount = 1,
		RequiresNearby = "Campfire",
		Description = "Cures poison and bleeding.",
	},
	SurvivalTonic = {
		DisplayName = "Survival Tonic",
		Cost = { MedicinalHerb = 2, Berries = 2, Fiber = 1 },
		Result = "SurvivalTonic",
		Amount = 1,
		Description = "Restores thirst, hunger, and a little health.",
	},
}

SurvivalConfig.CraftingCategories = {
	{
		Id = "Survival",
		DisplayName = "Survival",
		Description = "Early tools, food, and first-aid.",
		Recipes = { "StoneAxe", "Pickaxe", "Spear", "CampfireKit" },
	},
	{
		Id = "Food",
		DisplayName = "Food",
		Description = "Cooked meals and warmth recovery.",
		Recipes = { "CookedBerries", "CookedMeat", "MushroomStew" },
	},
	{
		Id = "Medicine",
		DisplayName = "Medicine",
		Description = "Stabilize, cure, and recover.",
		Recipes = { "Bandage", "Antidote", "SurvivalTonic" },
	},
	{
		Id = "Building",
		DisplayName = "Building",
		Description = "Shelter, storage, utilities, and structures.",
		Recipes = {
			"TorchStandKit",
			"ShelterKit",
			"WoodenWallKit",
			"WoodenDoorKit",
			"WoodenStairsKit",
			"StorageChestKit",
			"RainCollectorKit",
			"WorkbenchKit",
			"WatchtowerKit",
			"SpikeTrapKit",
			"SignalBeaconKit",
		},
	},
	{
		Id = "Advanced",
		DisplayName = "Advanced",
		Description = "Workbench and forge progression gear.",
		Recipes = { "ForgeKit", "IronIngot", "IronSpear", "HideArmor", "FurVest", "IronArmor" },
	},
}

SurvivalConfig.Shops = {
	CampTrader = {
		DisplayName = "Camp Trader",
		PromptText = "Trade",
		Description = "Starter tools, field food, and camp basics.",
		AccentColor = Color3.fromRGB(216, 169, 86),
		CounterColor = Color3.fromRGB(104, 69, 42),
		StockTheme = "General",
		WorldPositions = {
			Vector3.new(24, 0, 52),
			Vector3.new(360, 0, 345),
		},
		Catalog = {
			{
				Id = "ShopBandage",
				DisplayName = "Bandage",
				ItemId = "Bandage",
				Amount = 1,
				Cost = { Fiber = 2, Berries = 1 },
			},
			{
				Id = "ShopCookedBerries",
				DisplayName = "Cooked Berries",
				ItemId = "CookedBerries",
				Amount = 1,
				Cost = { Berries = 3, Wood = 1 },
			},
			{
				Id = "ShopStoneAxe",
				DisplayName = "Stone Axe",
				ItemId = "StoneAxe",
				Amount = 1,
				Cost = { Wood = 3, Stone = 4, Fiber = 2 },
			},
			{
				Id = "ShopPickaxe",
				DisplayName = "Pickaxe",
				ItemId = "Pickaxe",
				Amount = 1,
				Cost = { Wood = 4, Stone = 5, Fiber = 2 },
			},
			{
				Id = "ShopCampfireKit",
				DisplayName = "Campfire Kit",
				ItemId = "CampfireKit",
				Amount = 1,
				Cost = { Wood = 5, Stone = 3 },
			},
			{
				Id = "ShopTorchStandKit",
				DisplayName = "Torch Stand Kit",
				ItemId = "TorchStandKit",
				Amount = 1,
				Cost = { Wood = 3, Stone = 1, Fiber = 1 },
			},
		},
	},
	ForgeSmith = {
		DisplayName = "Forge Smith",
		PromptText = "Barter",
		Description = "Metal work, forge parts, and iron-tier gear.",
		AccentColor = Color3.fromRGB(215, 102, 58),
		CounterColor = Color3.fromRGB(82, 72, 66),
		StockTheme = "Forge",
		WorldPositions = {
			Vector3.new(-352, 0, 290),
			Vector3.new(575, 0, 42),
		},
		Catalog = {
			{
				Id = "SmithPickaxe",
				DisplayName = "Reinforced Pickaxe",
				ItemId = "Pickaxe",
				Amount = 1,
				Cost = { Wood = 4, Stone = 6, Fiber = 2 },
			},
			{
				Id = "SmithIngot",
				DisplayName = "Iron Ingot",
				ItemId = "IronIngot",
				Amount = 1,
				Cost = { IronOre = 2, Wood = 1 },
			},
			{
				Id = "SmithForgeKit",
				DisplayName = "Forge Kit",
				ItemId = "ForgeKit",
				Amount = 1,
				Cost = { Stone = 14, Wood = 6, IronOre = 2 },
			},
			{
				Id = "SmithIronSpear",
				DisplayName = "Iron Spear",
				ItemId = "IronSpear",
				Amount = 1,
				Cost = { IronIngot = 4, Wood = 3, Fiber = 2 },
			},
			{
				Id = "SmithIronArmor",
				DisplayName = "Iron Armor",
				ItemId = "IronArmor",
				Amount = 1,
				Cost = { IronIngot = 7, Hide = 3, AncientScrap = 2 },
			},
		},
	},
	Herbalist = {
		DisplayName = "Fen Herbalist",
		PromptText = "Trade",
		Description = "Medicine, tonics, and water survival supplies.",
		AccentColor = Color3.fromRGB(111, 184, 123),
		CounterColor = Color3.fromRGB(63, 91, 65),
		StockTheme = "Medic",
		WorldPositions = {
			Vector3.new(322, 0, -286),
			Vector3.new(-580, 0, -20),
		},
		Catalog = {
			{
				Id = "HerbBandage",
				DisplayName = "Bandage",
				ItemId = "Bandage",
				Amount = 2,
				Cost = { Fiber = 4, Berries = 1 },
			},
			{
				Id = "HerbAntidote",
				DisplayName = "Antidote",
				ItemId = "Antidote",
				Amount = 1,
				Cost = { MedicinalHerb = 2, Mushrooms = 1, Berries = 1 },
			},
			{
				Id = "HerbTonic",
				DisplayName = "Survival Tonic",
				ItemId = "SurvivalTonic",
				Amount = 1,
				Cost = { MedicinalHerb = 3, Berries = 2, Fiber = 1 },
			},
			{
				Id = "HerbStew",
				DisplayName = "Mushroom Stew",
				ItemId = "MushroomStew",
				Amount = 1,
				Cost = { Mushrooms = 3, Berries = 2, Wood = 1 },
			},
			{
				Id = "HerbRainCollector",
				DisplayName = "Rain Collector Kit",
				ItemId = "RainCollectorKit",
				Amount = 1,
				Cost = { Wood = 5, Fiber = 4, Stone = 2 },
			},
		},
	},
	BuilderDepot = {
		DisplayName = "Builder Depot",
		PromptText = "Trade",
		Description = "Shelter, storage, and defensive construction kits.",
		AccentColor = Color3.fromRGB(188, 150, 96),
		CounterColor = Color3.fromRGB(92, 65, 45),
		StockTheme = "Builder",
		WorldPositions = {
			Vector3.new(-26, 0, 54),
			Vector3.new(-345, 0, 326),
		},
		Catalog = {
			{
				Id = "BuilderWall",
				DisplayName = "Wooden Wall Kit",
				ItemId = "WoodenWallKit",
				Amount = 2,
				Cost = { Wood = 13, Leaves = 3, Fiber = 3 },
			},
			{
				Id = "BuilderDoor",
				DisplayName = "Wooden Door Kit",
				ItemId = "WoodenDoorKit",
				Amount = 1,
				Cost = { Wood = 8, Fiber = 2 },
			},
			{
				Id = "BuilderStairs",
				DisplayName = "Wooden Stairs Kit",
				ItemId = "WoodenStairsKit",
				Amount = 1,
				Cost = { Wood = 8, Stone = 1 },
			},
			{
				Id = "BuilderChest",
				DisplayName = "Storage Chest Kit",
				ItemId = "StorageChestKit",
				Amount = 1,
				Cost = { Wood = 9, Fiber = 3 },
			},
			{
				Id = "BuilderWorkbench",
				DisplayName = "Workbench Kit",
				ItemId = "WorkbenchKit",
				Amount = 1,
				Cost = { Wood = 10, Stone = 5, Fiber = 4 },
			},
			{
				Id = "BuilderWatchtower",
				DisplayName = "Watchtower Kit",
				ItemId = "WatchtowerKit",
				Amount = 1,
				Cost = { Wood = 22, Stone = 6, Fiber = 8 },
			},
			{
				Id = "BuilderSpikes",
				DisplayName = "Spike Trap Kit",
				ItemId = "SpikeTrapKit",
				Amount = 1,
				Cost = { Wood = 6, Stone = 5, Fiber = 2 },
			},
		},
	},
	Provisioner = {
		DisplayName = "Trail Provisioner",
		PromptText = "Trade",
		Description = "Food, hunting gear, and shelter supplies for long runs.",
		AccentColor = Color3.fromRGB(142, 178, 95),
		CounterColor = Color3.fromRGB(81, 70, 48),
		StockTheme = "Food",
		WorldPositions = {
			Vector3.new(-316, 0, -300),
			Vector3.new(372, 0, 300),
		},
		Catalog = {
			{
				Id = "ProvisionBerries",
				DisplayName = "Berries",
				ItemId = "Berries",
				Amount = 4,
				Cost = { Fiber = 2 },
			},
			{
				Id = "ProvisionCookedMeat",
				DisplayName = "Cooked Meat",
				ItemId = "CookedMeat",
				Amount = 1,
				Cost = { RawMeat = 2, Wood = 1 },
			},
			{
				Id = "ProvisionSpear",
				DisplayName = "Spear",
				ItemId = "Spear",
				Amount = 1,
				Cost = { Wood = 4, Stone = 3, Fiber = 3 },
			},
			{
				Id = "ProvisionShelter",
				DisplayName = "Shelter Kit",
				ItemId = "ShelterKit",
				Amount = 1,
				Cost = { Wood = 11, Leaves = 5, Fiber = 6 },
			},
			{
				Id = "ProvisionHideArmor",
				DisplayName = "Hide Armor",
				ItemId = "HideArmor",
				Amount = 1,
				Cost = { Hide = 5, Fiber = 5, Berries = 2 },
			},
		},
	},
	RelicBroker = {
		DisplayName = "Relic Broker",
		PromptText = "Barter",
		Description = "Rare salvage for beacon progression and late survival.",
		AccentColor = Color3.fromRGB(151, 128, 218),
		CounterColor = Color3.fromRGB(58, 52, 76),
		StockTheme = "Relic",
		WorldPositions = {
			Vector3.new(10, 0, -565),
			Vector3.new(585, 0, 35),
		},
		Catalog = {
			{
				Id = "RelicScrap",
				DisplayName = "Ancient Scrap",
				ItemId = "AncientScrap",
				Amount = 2,
				Cost = { IronOre = 2, MedicinalHerb = 1 },
			},
			{
				Id = "RelicTonic",
				DisplayName = "Survival Tonic",
				ItemId = "SurvivalTonic",
				Amount = 1,
				Cost = { AncientScrap = 1, Berries = 3, MedicinalHerb = 2 },
			},
			{
				Id = "RelicSpikeTrap",
				DisplayName = "Spike Trap Kit",
				ItemId = "SpikeTrapKit",
				Amount = 2,
				Cost = { AncientScrap = 2, Wood = 8, Stone = 6 },
			},
			{
				Id = "RelicBeacon",
				DisplayName = "Signal Beacon Kit",
				ItemId = "SignalBeaconKit",
				Amount = 1,
				Cost = { AncientScrap = 4, IronIngot = 5, SurvivalTonic = 1 },
			},
			{
				Id = "AntlerTrade",
				DisplayName = "Trade Antler",
				ItemId = "AncientScrap",
				Amount = 2,
				Cost = { Antler = 1 },
			},
		},
	},
}

SurvivalConfig.Consumables = {
	RawMeat = {
		Hunger = 18,
		Thirst = -8,
		StatusChance = { Poisoned = 0.35 },
		Notify = "Raw meat helps, but it is risky.",
	},
	Berries = {
		Hunger = 10,
		Thirst = 5,
		Notify = "You ate berries.",
	},
	Mushrooms = {
		Hunger = 12,
		Thirst = -2,
		StatusChance = { Poisoned = 0.12 },
		Notify = "You ate wild mushrooms.",
	},
	CookedBerries = {
		Hunger = 28,
		Thirst = 12,
		Notify = "Warm food steadies you.",
	},
	CookedMeat = {
		Hunger = 44,
		Thirst = -4,
		Notify = "Cooked meat gives you strength.",
	},
	MushroomStew = {
		Hunger = 38,
		Thirst = 14,
		Health = 8,
		Notify = "Mushroom stew warms you through.",
	},
	Bandage = {
		Health = 35,
		RemoveStatuses = { Bleeding = true },
		Notify = "You patched yourself up.",
	},
	Antidote = {
		RemoveStatuses = { Bleeding = true, Poisoned = true },
		Health = 8,
		Notify = "The antidote clears your blood.",
	},
	SurvivalTonic = {
		Hunger = 14,
		Thirst = 30,
		Health = 18,
		RemoveStatuses = { Bleeding = true, Poisoned = true },
		Notify = "The tonic steadies your body.",
	},
}

SurvivalConfig.Buildables = {
	CampfireKit = {
		ModelName = "Campfire",
		DisplayName = "Campfire",
		Radius = 24,
		LifetimeSeconds = 0,
		FuelSeconds = 220,
		MaxFuelSeconds = 420,
		LowFuelThreshold = 45,
		RefuelItem = "Wood",
		RefuelAmount = 2,
		RefuelSeconds = 100,
	},
	TorchStandKit = {
		ModelName = "TorchStand",
		DisplayName = "Torch Stand",
		Radius = 10,
		LifetimeSeconds = 0,
	},
	ShelterKit = {
		ModelName = "Shelter",
		DisplayName = "Shelter",
		Radius = 18,
		LifetimeSeconds = 0,
	},
	RainCollectorKit = {
		ModelName = "RainCollector",
		DisplayName = "Rain Collector",
		Radius = 12,
		LifetimeSeconds = 0,
		DrinkThirst = 26,
	},
	WorkbenchKit = {
		ModelName = "Workbench",
		DisplayName = "Workbench",
		Radius = 18,
		LifetimeSeconds = 0,
	},
	WoodenWallKit = {
		ModelName = "WoodenWall",
		DisplayName = "Wooden Wall",
		Radius = 8,
		LifetimeSeconds = 0,
	},
	WoodenDoorKit = {
		ModelName = "WoodenDoor",
		DisplayName = "Wooden Door",
		Radius = 8,
		LifetimeSeconds = 0,
	},
	WoodenStairsKit = {
		ModelName = "WoodenStairs",
		DisplayName = "Wooden Stairs",
		Radius = 8,
		LifetimeSeconds = 0,
	},
	StorageChestKit = {
		ModelName = "StorageChest",
		DisplayName = "Storage Chest",
		Radius = 9,
		LifetimeSeconds = 0,
		StorageItems = { "Wood", "Leaves", "Stone", "Fiber", "IronOre", "IronIngot", "AncientScrap", "MedicinalHerb", "Hide", "Fur", "Antler" },
		TransferAmount = 10,
	},
	WatchtowerKit = {
		ModelName = "Watchtower",
		DisplayName = "Watchtower",
		Radius = 18,
		ShelterRadius = 16,
		LifetimeSeconds = 0,
	},
	ForgeKit = {
		ModelName = "Forge",
		DisplayName = "Forge",
		Radius = 18,
		LifetimeSeconds = 0,
	},
	SpikeTrapKit = {
		ModelName = "SpikeTrap",
		DisplayName = "Spike Trap",
		Radius = 9,
		LifetimeSeconds = 0,
		Damage = 45,
		Charges = 4,
	},
	SignalBeaconKit = {
		ModelName = "SignalBeacon",
		DisplayName = "Signal Beacon",
		Radius = 20,
		LifetimeSeconds = 0,
	},
}

SurvivalConfig.CampComfort = {
	ShelterRest = {
		CooldownSeconds = 55,
		Health = 24,
		Hunger = -4,
		Thirst = -3,
		Temperature = 10,
		ApplyStatuses = { Rested = 80 },
	},
}

SurvivalConfig.Equipment = {
	StoneAxe = { Slot = "Weapon", MaxDurability = 45 },
	Pickaxe = { Slot = "Weapon", MaxDurability = 52 },
	Spear = { Slot = "Weapon", MaxDurability = 64 },
	IronSpear = { Slot = "Weapon", MaxDurability = 120 },
	HideArmor = { Slot = "Armor", MaxDurability = 95 },
	FurVest = { Slot = "Armor", MaxDurability = 75 },
	IronArmor = { Slot = "Armor", MaxDurability = 170 },
}

SurvivalConfig.Progression = {
	LevelThresholds = { 0, 80, 190, 340, 540, 790, 1100 },
	XP = {
		Harvest = 4,
		RareHarvest = 8,
		CacheSearch = 16,
		Craft = 12,
		Build = 18,
		EnemyHit = 4,
		EnemyDefeat = 38,
		NightSurvived = 52,
		StatusCured = 10,
		TrapTriggered = 14,
		BeaconUpgrade = 70,
		RegionDiscovered = 20,
		ShelterRest = 18,
	},
}

SurvivalConfig.Movement = {
	WalkSpeed = 16,
	SprintSpeed = 23,
	StaminaMax = 100,
	SprintDrainPerSecond = 16,
	StaminaRegenPerSecond = 12,
	ExhaustedThreshold = 10,
}

SurvivalConfig.Threat = {
	BaseThreat = 0,
	MaxThreat = 100,
	NightThreatPerTick = 4,
	StormThreatBonus = 2,
	HeatWaveThreatBonus = 1,
	DayThreatDecay = 1.5,
	RaidThreshold = 70,
	RaidCooldownSeconds = 55,
	RaidEnemyCount = 3,
	BeaconThreatPerStage = 12,
}

SurvivalConfig.SignalBeacon = {
	MaxStage = 3,
	UpgradeCost = {
		[1] = { AncientScrap = 2, IronIngot = 1 },
		[2] = { AncientScrap = 3, IronIngot = 2, Hide = 2 },
		[3] = { AncientScrap = 4, IronIngot = 3, SurvivalTonic = 1 },
	},
	StageNames = {
		[0] = "Dormant",
		[1] = "Frame Built",
		[2] = "Transmitter Tuned",
		[3] = "Signal Online",
	},
}

SurvivalConfig.StatusEffects = {
	Bleeding = {
		DisplayName = "Bleeding",
		DurationSeconds = 20,
		DamagePerTick = 2,
	},
	Poisoned = {
		DisplayName = "Poisoned",
		DurationSeconds = 34,
		DamagePerTick = 2,
		HungerLossPerTick = 0.6,
		ThirstLossPerTick = 0.9,
	},
	Soaked = {
		DisplayName = "Soaked",
		DurationSeconds = 28,
		TemperatureLossPerTick = 1.2,
		ThirstGainPerTick = 0.15,
	},
	Rested = {
		DisplayName = "Rested",
		DurationSeconds = 80,
		HealthPerTick = 1,
		TemperatureGainPerTick = 0.35,
	},
}

SurvivalConfig.Weather = {
	Clear = {
		DisplayName = "Clear",
		Weight = 42,
		TemperatureModifier = 0,
		HungerMultiplier = 1,
		ThirstMultiplier = 1,
		EnemyMultiplier = 1,
	},
	Rain = {
		DisplayName = "Rain",
		Weight = 24,
		TemperatureModifier = -8,
		HungerMultiplier = 1.05,
		ThirstMultiplier = 0.75,
		EnemyMultiplier = 0.9,
		ExposureStatus = "Soaked",
		ExposureChance = 0.16,
	},
	ColdFront = {
		DisplayName = "Cold Front",
		Weight = 14,
		TemperatureModifier = -22,
		HungerMultiplier = 1.18,
		ThirstMultiplier = 0.95,
		EnemyMultiplier = 1.15,
	},
	HeatWave = {
		DisplayName = "Heat Wave",
		Weight = 10,
		TemperatureModifier = 18,
		HungerMultiplier = 1,
		ThirstMultiplier = 1.65,
		EnemyMultiplier = 0.8,
	},
	Storm = {
		DisplayName = "Storm",
		Weight = 10,
		TemperatureModifier = -14,
		HungerMultiplier = 1.2,
		ThirstMultiplier = 1.1,
		EnemyMultiplier = 1.35,
		FuelDrainMultiplier = 1.45,
		ExposureStatus = "Soaked",
		ExposureChance = 0.28,
	},
}

SurvivalConfig.Combat = {
	DefaultDamage = 8,
	DefaultRange = 10,
	CooldownSeconds = 0.68,
	Weapons = {
		StoneAxe = { Damage = 16, Range = 12 },
		Pickaxe = { Damage = 18, Range = 12 },
		Spear = { Damage = 26, Range = 17 },
		IronSpear = { Damage = 38, Range = 18 },
	},
	Armor = {
		HideArmor = { DamageMultiplier = 0.65 },
		FurVest = { DamageMultiplier = 0.80 },
		IronArmor = { DamageMultiplier = 0.45 },
	},
}

SurvivalConfig.Enemies = {
	NightStalker = {
		DisplayName = "Night Stalker",
		Health = 72,
		Damage = 13,
		AttackRange = 5.5,
		AggroRange = 95,
		MoveSpeed = 18,
		SpawnEverySeconds = 16,
		MaxAlive = 7,
		BleedChance = 0.18,
		Drop = {
			RawMeat = { Min = 1, Max = 2 },
			Hide = { Min = 1, Max = 2 },
		},
	},
}

SurvivalConfig.Objectives = {
	GatherBasics = {
		DisplayName = "First Supplies",
		Description = "Gather wood, stone, fiber, and berries.",
		Kind = "Collect",
		Requirements = { Wood = 4, Stone = 3, Fiber = 3, Berries = 2 },
		Reward = { Bandage = 1 },
	},
	ExploreRegions = {
		DisplayName = "Scout The Island",
		Description = "Discover three named regions.",
		Kind = "Counter",
		Counter = "RegionsDiscovered",
		Required = 3,
		Reward = { CookedBerries = 2, MedicinalHerb = 2 },
	},
	MakeWeapons = {
		DisplayName = "Armed For Night",
		Description = "Craft a stone axe and a spear.",
		Kind = "Craft",
		Requirements = { StoneAxe = 1, Spear = 1 },
		Reward = { CookedBerries = 1 },
	},
	BuildCamp = {
		DisplayName = "Hold The Camp",
		Description = "Place a campfire, shelter, and workbench.",
		Kind = "Build",
		Requirements = { Campfire = 1, Shelter = 1, Workbench = 1 },
		Reward = { SurvivalTonic = 1 },
	},
	BuildShelterWalls = {
		DisplayName = "Build A Shelter",
		Description = "Place two wooden walls, one wooden door, and one storage chest.",
		Kind = "Build",
		Requirements = { WoodenWall = 2, WoodenDoor = 1, StorageChest = 1 },
		Reward = { TorchStandKit = 1, CookedBerries = 1 },
	},
	SearchCaches = {
		DisplayName = "Scavenge The Old World",
		Description = "Search three abandoned caches.",
		Kind = "Counter",
		Counter = "CachesSearched",
		Required = 3,
		Reward = { AncientScrap = 2, MedicinalHerb = 2 },
	},
	BuildDefenses = {
		DisplayName = "Defensive Line",
		Description = "Place two spike traps.",
		Kind = "Build",
		Requirements = { SpikeTrap = 2 },
		Reward = { IronOre = 3 },
	},
	RestAtShelter = {
		DisplayName = "Recover At Shelter",
		Description = "Rest at a placed shelter.",
		Kind = "Counter",
		Counter = "ShelterRests",
		Required = 1,
		Reward = { CookedBerries = 1, Bandage = 1 },
	},
	ForgeIron = {
		DisplayName = "Iron Age",
		Description = "Place a forge and craft an iron spear.",
		Kind = "Craft",
		Requirements = { ForgeKit = 1, IronSpear = 1 },
		Reward = { Antidote = 2 },
	},
	SignalForRescue = {
		DisplayName = "Signal For Rescue",
		Description = "Upgrade the signal beacon to stage three.",
		Kind = "Counter",
		Counter = "BeaconStage",
		Required = 3,
		Reward = { IronArmor = 1 },
	},
	HuntStalkers = {
		DisplayName = "Night Hunter",
		Description = "Defeat three night stalkers.",
		Kind = "Counter",
		Counter = "EnemiesDefeated",
		Required = 3,
		Reward = { Hide = 2, RawMeat = 2 },
	},
	SurviveNight = {
		DisplayName = "See The Dawn",
		Description = "Survive one full night.",
		Kind = "Counter",
		Counter = "NightsSurvived",
		Required = 1,
		Reward = { Spear = 1 },
	},
}


SurvivalConfig.Wildlife = {
	Rabbit = {
		DisplayName = "Rabbit",
		Health = 18,
		MoveSpeed = 22,
		WanderRadius = 28,
		WanderIntervalSeconds = 4,
		FleeRange = 24,
		FleeSpeed = 30,
		FleeDurationSeconds = 5,
		SpawnEverySeconds = 20,
		MaxAlive = 8,
		SpawnRegions = { "AshwoodHollow", "GlacierScar", "CinderHarbour", "BrimstoneMarsh" },
		Drop = {
			RawMeat = { Min = 1, Max = 2 },
			Fur = { Min = 1, Max = 2 },
		},
	},
	Deer = {
		DisplayName = "Deer",
		Health = 55,
		MoveSpeed = 14,
		WanderRadius = 50,
		WanderIntervalSeconds = 6,
		FleeRange = 40,
		FleeSpeed = 24,
		FleeDurationSeconds = 8,
		SpawnEverySeconds = 30,
		MaxAlive = 5,
		SpawnRegions = { "AshwoodHollow", "GlacierScar", "BrimstoneMarsh" },
		Drop = {
			RawMeat = { Min = 2, Max = 4 },
			Hide = { Min = 1, Max = 2 },
			Antler = { Min = 0, Max = 1 },
		},
	},
}

return SurvivalConfig
